### ISSUE TITLE
Replacement for MIC5265-3.3YD5-TR

### ISSUE THREAD

**Issue by HSBallina** [dojoe/roland-mram-card#5]
Since the MIC5265-3.3YD5-TR seems to be out of stock in most places, would the [MIC5245-3.3YM5-TR](https://www.mouser.se/ProductDetail/?qs=U6T8BxXiZAXkopuvjIDr5w%3D%3D) be a suitable replacement?

**Comment by dojoe** [comment]
Yes, looks like it would. The footprint and parameters match the application. The most critical thing is device height - during early design I switched to the Micrel part from a different part (don't remember which) because that other part was too high and the card would not fit in the slot :) The MIC5245 is 1.45mm max like the MIC5265 so that's not a problem.

**Comment by HSBallina** [comment]
Awesome, thank you :)
